apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-taik
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0036-tenant/tkrw-pr714-0075-0036-app/devfile-sample-taik@sha256:7c3d6168f3dce9e80802a4fae6b1f94c69d371b9807f1b33a86f63f56373d3e2
        name: my-nodejs
        resources: {}
status: {}
